nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['https://bewved.onrender.com/']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: false
    paths:
        '^/': 
            allow_credentials: false
            allow_origin: ['https://bewved.onrender.com/']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            expose_headers: []
            max_age: 3600
            hosts: []
            origin_regex: false