# Routes for FormationController
app_formation_index:
    path: /formation/
    controller: App\Controller\FormationController::getAllFormations
    methods: ['GET']

app_formation_new:
    path: /formation/new/
    controller: App\Controller\FormationController::new
    methods: ['GET', 'POST']

app_formation_show:
    path: /formation/{id}
    controller: App\Controller\FormationController::show
    methods: ['GET']
    requirements:
        id: '\d+'

app_formation_edit:
    path: /formation/{id}/edit/
    controller: App\Controller\FormationController::edit
    methods: ['PUT']
    requirements:
        id: '\d+'

app_formation_delete:
    path: /formation/{id}
    controller: App\Controller\FormationController::delete
    methods: ['DELETE']
    requirements:
        id: '\d+'

app_formation_addgroup:
    path: /formation/{id}/addgroup/
    controller: App\Controller\FormationController::addGroup
    methods: ['POST']
    requirements:
        id: '\d+'