# config/routes/promotion.yaml

app_promotion_index:
    path: /promotion/
    controller: App\Controller\PromotionController::getAllPromotions
    methods: [GET]

app_promotion_new:
    path: /promotion/new
    controller: App\Controller\PromotionController::new
    methods: [POST]

app_promotion_show:
    path: /promotion/{id}
    controller: App\Controller\PromotionController::show
    methods: [GET]

app_promotion_update:
    path: /promotion/{id}/edit
    controller: App\Controller\PromotionController::edit
    methods: [PUT]

app_promotion_delete:
    path: /promotion/{id}
    controller: App\Controller\PromotionController::delete
    methods: [DELETE]
